"""Typer CLI entry point for Agentic AutoRAG."""

from __future__ import annotations

import asyncio
import logging
import platform
import shutil
from pathlib import Path

import typer

from agentic_autorag.litellm_runtime import configure_litellm_runtime

app = typer.Typer(name="agentic-autorag", help="Agentic AutoRAG Optimizer")


@app.command()
def optimize(
    config: str = typer.Option("configs/starter_example.yaml", help="Path to YAML config"),
    verbose: bool = typer.Option(False, "--verbose", "-v", help="Enable verbose/debug logging"),
    debug_eval_samples: int = typer.Option(
        0,
        "--debug-eval-samples",
        help="Log N sampled question/retrieved-context/RAG-answer triples per trial to run.log "
        "(0 disables). Useful for diagnosing whether high accuracy reflects easy questions vs. "
        "real RAG quality.",
    ),
    seed: int | None = typer.Option(
        None,
        "--seed",
        help="Forwarded to the proposer LLM as ``seed=``. Providers that honour seed "
        "(OpenAI, Bedrock-Anthropic) become deterministic given identical inputs; "
        "others silently drop it via litellm.drop_params. Used by multi-seed "
        "benchmark runs to vary the agent across seeds.",
    ),
    force_verify: bool = typer.Option(
        False,
        "--force-verify",
        help="Ignore the LLM endpoint verification cache and re-ping every model "
        "in the search space. Use after fixing a previously-failing endpoint.",
    ),
    skip_final_report: bool = typer.Option(
        False,
        "--skip-final-report",
        help="Skip the LLM-written optimization_summary.md at end of run. The report "
        "is generated by the optimizer model (one extra call, a few cents); skip it "
        "for fast iteration or scripted runs that only consume recommended.yaml.",
    ),
) -> None:
    """Run the optimization loop."""
    configure_litellm_runtime()

    logging.basicConfig(
        level=logging.DEBUG if verbose else logging.WARNING,
        format="%(levelname)s: %(name)s: %(message)s",
    )
    from agentic_autorag.orchestrator import Orchestrator  # triggers lightrag import

    if not verbose:
        # LightRAG resets its own logger to INFO at module-load, so we silence it
        # AFTER the import above — otherwise our setLevel gets clobbered.
        logging.getLogger("lightrag").setLevel(logging.WARNING)

    from pydantic import ValidationError

    # Construction loads + validates the config and checks API keys. Turn the
    # common setup failures into concise, actionable messages instead of a raw
    # traceback. Runtime failures inside run() still surface in full.
    try:
        orchestrator = Orchestrator(
            config,
            debug_eval_samples=debug_eval_samples,
            seed=seed,
            force_verify=force_verify,
            skip_final_report=skip_final_report,
        )
    except FileNotFoundError as exc:
        typer.secho(f"Config error: {exc}", fg=typer.colors.RED, err=True)
        typer.echo(
            "  Pass --config <path>; see configs/starter_example.yaml for a template.",
            err=True,
        )
        raise typer.Exit(1) from exc
    except ValidationError as exc:
        typer.secho(f"Invalid config ({config}):", fg=typer.colors.RED, err=True)
        for err in exc.errors():
            loc = ".".join(str(p) for p in err["loc"]) or "(root)"
            typer.echo(f"  {loc}: {err['msg']}", err=True)
        typer.echo(
            "  See configs/full_example.yaml and agentic_autorag/config/models.py for the schema.",
            err=True,
        )
        raise typer.Exit(1) from exc
    except (ValueError, OSError) as exc:
        # Empty/garbled YAML (ValueError from the loader) or missing API keys
        # (OSError from _check_api_keys) — both carry actionable text already.
        typer.secho(str(exc), fg=typer.colors.RED, err=True)
        raise typer.Exit(1) from exc

    asyncio.run(orchestrator.run())


def _exam_summary_lines(exam: list, exam_path: Path) -> list[str]:
    """Render a saturation summary for a generated/loaded exam.

    Pure over the question list so it is unit-testable without a live run.
    The probe ladder (per-tier solve rate, weakest->strongest) and the
    k-distribution (how many probes solved each question) are the saturation
    signal: a healthy exam has a monotone-increasing ladder and an empty
    saturated bucket (k == n_probes).
    """
    from collections import Counter

    lines = [f"Exam: {len(exam)} questions  ->  {exam_path}"]
    if not exam:
        return lines

    probed = [q for q in exam if q.probe_outcomes]
    if probed:
        n_probes = max(len(q.probe_outcomes) for q in probed)
        k_hist = Counter(sum(q.probe_outcomes) for q in probed)
        rates = [
            sum(q.probe_outcomes[i] for q in probed if len(q.probe_outcomes) > i)
            / sum(1 for q in probed if len(q.probe_outcomes) > i)
            for i in range(n_probes)
        ]
        lines.append("  probe ladder (solve rate, weakest->strongest): " + ", ".join(f"{r:.2f}" for r in rates))
        monotone = all(rates[i] <= rates[i + 1] + 1e-9 for i in range(len(rates) - 1))
        if not monotone:
            lines.append("  WARNING: ladder is NON-MONOTONE — a stronger probe scored below a weaker one")
            lines.append("           (probe mis-calibration / throttling, not exam difficulty)")
        lines.append("  k = #probes solving each question:")
        for k in range(n_probes + 1):
            lines.append(f"    k={k}: {k_hist.get(k, 0)}")
        lines.append(f"  too-hard  (k=0, no probe solved):       {k_hist.get(0, 0)}")
        lines.append(f"  saturated (k={n_probes}, every probe solved): {k_hist.get(n_probes, 0)}")
    else:
        lines.append("  (no probe outcomes recorded — probe_selection was off)")

    by_type = Counter(q.reasoning_type for q in exam)
    by_hops = Counter(q.num_hops for q in exam)
    n_multi_doc = sum(1 for q in exam if q.is_multi_doc)
    lines.append("  reasoning_type: " + ", ".join(f"{t}={c}" for t, c in by_type.most_common()))
    lines.append("  num_hops: " + ", ".join(f"{h}-hop={c}" for h, c in sorted(by_hops.items())))
    lines.append(f"  multi-doc: {n_multi_doc}/{len(exam)}")
    return lines


@app.command("generate-exam")
def generate_exam(
    config: str = typer.Option("configs/starter_example.yaml", help="Path to YAML config"),
    regen: bool = typer.Option(
        False,
        "--regen",
        "--force",
        help="Delete any cached exam/candidates and regenerate from scratch (keeps the "
        "corpus + embedding caches under .cache/, so only composition/probes re-run).",
    ),
    verbose: bool = typer.Option(False, "--verbose", "-v", help="Enable verbose/debug logging"),
) -> None:
    """Generate (or load) the frozen exam and stop — for testing exam generation in isolation.

    Runs everything ``optimize`` does up to and including exam generation (corpus
    parse, graph build if configured, compose -> validate -> probe-select), then
    stops before the trial loop and prints a saturation summary.
    """
    configure_litellm_runtime()

    logging.basicConfig(
        level=logging.DEBUG if verbose else logging.INFO,
        format="%(levelname)s: %(name)s: %(message)s",
    )
    from agentic_autorag.orchestrator import Orchestrator  # triggers lightrag import

    if not verbose:
        logging.getLogger("lightrag").setLevel(logging.WARNING)

    from pydantic import ValidationError

    # Construction mirrors `optimize` exactly so config/key errors read the same.
    try:
        orchestrator = Orchestrator(config)
    except FileNotFoundError as exc:
        typer.secho(f"Config error: {exc}", fg=typer.colors.RED, err=True)
        typer.echo(
            "  Pass --config <path>; see configs/starter_example.yaml for a template.",
            err=True,
        )
        raise typer.Exit(1) from exc
    except ValidationError as exc:
        typer.secho(f"Invalid config ({config}):", fg=typer.colors.RED, err=True)
        for err in exc.errors():
            loc = ".".join(str(p) for p in err["loc"]) or "(root)"
            typer.echo(f"  {loc}: {err['msg']}", err=True)
        typer.echo(
            "  See configs/full_example.yaml and agentic_autorag/config/models.py for the schema.",
            err=True,
        )
        raise typer.Exit(1) from exc
    except (ValueError, OSError) as exc:
        typer.secho(str(exc), fg=typer.colors.RED, err=True)
        raise typer.Exit(1) from exc

    if regen:
        for path in (
            orchestrator.cache_layout.exam,
            orchestrator.cache_layout.candidates,
            orchestrator.cache_layout.exam_cost,
        ):
            path.unlink(missing_ok=True)

    async def _run() -> None:
        try:
            await orchestrator.setup()
        finally:
            await orchestrator.cleanup()

    asyncio.run(_run())

    for line in _exam_summary_lines(orchestrator.exam, orchestrator.cache_layout.exam):
        print(line)


@app.command()
def info() -> None:
    """Print system info and check dependencies."""
    print(f"Python:   {platform.python_version()}")
    print(f"Platform: {platform.system()} {platform.machine()}")

    # Ollama
    ollama_path = shutil.which("ollama")
    if ollama_path:
        print(f"Ollama:   ✓ found at {ollama_path}")
    else:
        print("Ollama:   ✗ not found on PATH")

    # vLLM
    vllm_path = shutil.which("vllm")
    if vllm_path:
        print(f"vLLM:     ✓ found at {vllm_path}")
    else:
        print("vLLM:     ✗ not found on PATH (install: uv sync --extra dev)")

    # Key packages
    for pkg in ("lancedb", "litellm", "sentence_transformers", "pydantic", "typer"):
        try:
            mod = __import__(pkg)
            version = getattr(mod, "__version__", "unknown")
            print(f"{pkg:20s} ✓  {version}")
        except ImportError:
            print(f"{pkg:20s} ✗  not installed")


@app.command("benchmark-prepare")
def benchmark_prepare(
    name: str = typer.Argument(..., help="Benchmark name (e.g. 'hotpot_qa')"),
    output: str = typer.Option(..., "--output", "-o", help="Output directory for corpus + qa.json"),
    split: str = typer.Option("validation", help="Dataset split"),
    sample_size: int | None = typer.Option(500, "--sample-size", help="Deterministic sample size; omit for full split"),
    seed: int = typer.Option(42, help="Sampling seed"),
    hf_revision: str | None = typer.Option(None, "--hf-revision", help="Pin HuggingFace dataset revision"),
) -> None:
    """Download a benchmark and materialise it as corpus/ + qa.json + metadata.json."""
    from agentic_autorag.benchmarks import prepare as prepare_benchmark

    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(name)s: %(message)s")
    manifest = prepare_benchmark(
        name=name,
        output_dir=Path(output),
        split=split,
        sample_size=sample_size,
        seed=seed,
        hf_revision=hf_revision,
    )
    print(f"Prepared {manifest.name} ({manifest.split}, n={manifest.sample_size})")
    print(f"  corpus:   {Path(output) / 'corpus'}  ({manifest.corpus_doc_count} docs)")
    print(f"  qa:       {Path(output) / 'qa.json'}")
    print(f"  metadata: {Path(output) / 'metadata.json'}  (hf_revision={manifest.hf_revision})")


@app.command("benchmark-evaluate")
def benchmark_evaluate(
    project_config: str = typer.Option(..., "--project-config", help="Path to the project YAML used for optimize"),
    trial_config: str = typer.Option(
        ..., "--trial-config", help="Path to a TrialConfig YAML (e.g. recommended.yaml or any frontier/trial_NN.yaml)"
    ),
    qa: str = typer.Option(..., "--qa", help="Path to benchmark qa.json"),
    output: str = typer.Option(..., "--output", "-o", help="Destination for benchmark_results.json"),
    judge_model: str | None = typer.Option(
        None, "--judge-model", help="LiteLLM model string for LLM-as-judge; omit to skip"
    ),
    concurrency: int = typer.Option(10, help="Concurrent questions under evaluation"),
    limit: int | None = typer.Option(
        None, "--limit", "-n", help="Evaluate only the first N questions; omit to use all"
    ),
    verbose: bool = typer.Option(False, "--verbose", "-v"),
) -> None:
    """Score a (project_config, trial_config) pair against held-out benchmark QA."""
    configure_litellm_runtime()
    logging.basicConfig(
        level=logging.DEBUG if verbose else logging.WARNING,
        format="%(levelname)s: %(name)s: %(message)s",
    )
    # Chatty libraries — we want their warnings, not their per-call INFO lines.
    if not verbose:
        for noisy in ("LiteLLM", "litellm", "sentence_transformers", "httpx"):
            logging.getLogger(noisy).setLevel(logging.WARNING)

    # User-facing progress goes through agentic_autorag.run — same dedicated
    # logger the orchestrator uses for `optimize`, with a bare %(message)s format
    # and propagate=False so root-handler prefixes don't leak in.
    run_logger = logging.getLogger("agentic_autorag.run")
    run_logger.setLevel(logging.DEBUG if verbose else logging.INFO)
    run_logger.propagate = False
    for handler in list(run_logger.handlers):
        run_logger.removeHandler(handler)
    console = logging.StreamHandler()
    console.setLevel(logging.DEBUG if verbose else logging.INFO)
    console.setFormatter(logging.Formatter("%(message)s"))
    run_logger.addHandler(console)

    from agentic_autorag.benchmark_eval.runner import run as run_eval

    if limit is not None and limit <= 0:
        raise typer.BadParameter("--limit must be a positive integer", param_hint="--limit")

    asyncio.run(
        run_eval(
            project_config_path=project_config,
            trial_config_path=trial_config,
            qa_path=qa,
            output_path=output,
            judge_model=judge_model,
            concurrency=concurrency,
            limit=limit,
        )
    )


@app.command()
def clean(
    config: str = typer.Option("configs/starter_example.yaml", help="Path to YAML config"),
    yes: bool = typer.Option(False, "--yes", "-y", help="Skip confirmation prompt"),
) -> None:
    """Remove all generated artifacts for a fresh optimization run.

    Deletes the corpus cache, exam cache, ingredient cache, LanceDB working
    dir, history, exam, logs, and best config from the output directory.
    """
    from agentic_autorag.config.loader import load_config
    from agentic_autorag.output_layout import RunLayout

    search_space = load_config(config)
    output_dir = Path(search_space.meta.output_dir)

    if not output_dir.exists():
        print(f"Nothing to clean — output directory does not exist: {output_dir}")
        raise typer.Exit()

    layout = RunLayout(base=output_dir)
    targets = [
        (output_dir / ".cache", "Corpus + exam + ingredient cache"),
        (layout.details, "History, cost ledgers, candidates + debug artifacts"),
        (layout.exam, "Exam questions"),
        (layout.recommended, "Recommended config"),
        (layout.summary, "Optimization summary report"),
        (layout.frontier_dir, "Frontier configs directory"),
        (output_dir / "benchmark_results.json", "Benchmark results"),
        (layout.run_log, "Run log"),
    ]

    found = [(path, label) for path, label in targets if path.exists()]

    if not found:
        print(f"Nothing to clean in {output_dir}")
        raise typer.Exit()

    print(f"Will delete from {output_dir}:")
    for path, label in found:
        print(f"  {label:20s}  {path.name}")

    if not yes:
        typer.confirm("Proceed?", abort=True)

    for path, label in found:
        if path.is_dir():
            shutil.rmtree(path)
        else:
            path.unlink()
        print(f"  Removed {label}")

    print("Done — ready for a fresh run.")


if __name__ == "__main__":
    app()
