"""Drive AutoRAG's native synthetic QA generation (``autorag.data.qa``).

AutoRAG's data-creation pipeline lives behind imports we can't perform in our
venv (numpy<2 conflict), so this module shells out to the AutoRAG-venv Python
interpreter (``AUTORAG_PYTHON`` env var) with a small generator script.

The generator script is materialised at runtime in the run's output directory
so reviewers can audit exactly what AutoRAG saw.
"""

from __future__ import annotations

import logging
import os
import subprocess
import textwrap
from pathlib import Path

logger = logging.getLogger("agentic_autorag.run")

_GENERATOR_TEMPLATE = textwrap.dedent(
    '''
    """Bootstrap AutoRAG QA from a corpus.parquet using the RAGAS-style pipeline.

    Auto-generated by agentic_autorag.baselines.autorag.qa_ragas; do not edit
    by hand — re-running the baseline driver overwrites this file.
    """

    import pandas as pd

    from autorag.data.qa.sample import random_single_hop
    from autorag.data.qa.query.openai_gen_query import factoid_query_gen
    from autorag.data.qa.generation_gt.openai_gen_gt import make_basic_gen_gt
    from autorag.data.qa.filter.dontknow import dontknow_filter_rule_based
    from autorag.data.qa.schema import Raw

    CORPUS_PARQUET = {corpus_parquet!r}
    OUTPUT_PARQUET = {output_parquet!r}
    SAMPLE_N = {sample_n}
    LLM_MODEL = {llm_model!r}

    raw = Raw.from_parquet(CORPUS_PARQUET)
    sampled = raw.sample(random_single_hop, n=SAMPLE_N)
    qa = sampled.batch_apply(factoid_query_gen, llm=LLM_MODEL)
    qa = qa.batch_apply(make_basic_gen_gt, llm=LLM_MODEL)
    qa = qa.filter(dontknow_filter_rule_based)
    qa.to_parquet(OUTPUT_PARQUET)
    print(f"Wrote {{len(qa.data)}} QA pairs to {{OUTPUT_PARQUET}}")
'''
).strip()


def export_ragas_qa_via_subprocess(
    corpus_parquet: Path,
    output_parquet: Path,
    *,
    sample_n: int,
    llm_model: str,
    autorag_python: str | None = None,
    workdir: Path | None = None,
) -> Path:
    """Run AutoRAG's QA bootstrap in a separate venv and return the output path.

    Parameters
    ----------
    corpus_parquet:
        Path to the corpus parquet AutoRAG will sample from.
    output_parquet:
        Where the generated qa.parquet should land.
    sample_n:
        Number of QA pairs to generate (mirrors our ``examiner.exam_size``).
    llm_model:
        LLM string AutoRAG passes to its query/generation modules.
    autorag_python:
        Path to the Python interpreter where AutoRAG is installed. Defaults to
        ``AUTORAG_PYTHON`` env var. If neither is set, raises ``RuntimeError``.
    workdir:
        Directory where the generator script is materialised. Defaults to the
        parent of ``output_parquet``.
    """
    autorag_python = autorag_python or os.environ.get("AUTORAG_PYTHON")
    if not autorag_python:
        raise RuntimeError(
            "AutoRAG is not in our venv (numpy conflict). Install it in a "
            "separate venv and pass --autorag-python /path/to/venv/bin/python "
            "or set the AUTORAG_PYTHON environment variable."
        )

    workdir = workdir or output_parquet.parent
    workdir.mkdir(parents=True, exist_ok=True)
    script_path = workdir / "_autorag_qa_ragas.py"
    script_path.write_text(
        _GENERATOR_TEMPLATE.format(
            corpus_parquet=str(corpus_parquet),
            output_parquet=str(output_parquet),
            sample_n=sample_n,
            llm_model=llm_model,
        ),
        encoding="utf-8",
    )

    logger.info("Running AutoRAG RAGAS QA bootstrap via %s", autorag_python)
    result = subprocess.run(
        [autorag_python, str(script_path)],
        check=False,
        capture_output=True,
        text=True,
    )
    if result.stdout:
        logger.info(result.stdout.rstrip())
    if result.stderr:
        logger.warning(result.stderr.rstrip())
    if result.returncode != 0:
        raise RuntimeError(
            f"AutoRAG QA bootstrap subprocess failed (rc={result.returncode}).\n"
            f"stdout:\n{result.stdout}\nstderr:\n{result.stderr}"
        )
    if not output_parquet.exists():
        raise RuntimeError(f"AutoRAG bootstrap completed but did not write {output_parquet}")
    return output_parquet
